---
- hosts: all
  become: yes
  become_user: isucon
  gather_facts: no
  tasks:
    - git:
        repo=https://github.com/tagomoris/xbuild.git
        dest=/home/isucon/.xbuild
        update=yes
    # golang
    - command: /home/isucon/.xbuild/go-install 1.7.3 /home/isucon/.local/go
      args:
        creates: /home/isucon/.local/go/bin/go
    - lineinfile: dest=/home/isucon/.profile regexp='^export GOROOT' line='export GOROOT=/home/isucon/.local/go'
    - lineinfile: dest=/home/isucon/.profile regexp='^export GOPATH' line='export GOPATH=/home/isucon/go'
    - lineinfile: dest=/home/isucon/.profile regexp='^export PATH.*GOPATH' line='export PATH="$GOPATH/bin:$GOROOT/bin:$PATH"'
