--- 
- hosts: all
  gather_facts: no
  become: yes
  tasks:
    - shell: |
        . /home/isucon/.profile
        go get github.com/jteeuwen/go-bindata/... 
        go get github.com/Masterminds/glide
        go get github.com/isucon/isucon6-final/bench/...
      args:
        chdir: ../../bench
    - shell: |
        . /home/isucon/.profile
        glide install
      args:
        chdir: ../../bench
    - shell: |
        . /home/isucon/.profile
        make isucon6f
      args:
        chdir: ../../bench
