--- 
- hosts: all
  gather_facts: no
  become: yes
  become_user: isucon
  tasks:
    - file:
        path=/home/isucon/isucon6f/
        state=directory
    - copy:
        src=../../../bench/isucon6f/bench
        dest=/home/isucon/isucon6f/bench
        mode=0755
    - copy:
        src=../../../bench/isucon6f/worker
        dest=/home/isucon/isucon6f/worker
        mode=0755

- hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: bench (systemd)
      template:
        src=../templates/isucon6-worker.service.j2
        dest=/etc/systemd/system/isucon6-worker.service
        owner=root
        group=root
        mode=644
    - name: enable bench worker
      service: name=isucon6-worker state=running enabled=true
  vars_files:
    - ../../external_vars.yml
