--- 
- hosts: all
  gather_facts: no
  become: yes
  become_user: isucon
  tasks:
    - copy:
        src=../../../bench/isucon6f/
        dest=/home/isucon/isucon6f/
    - file:
        path=/home/isucon/isucon6f/bench
        mode=0755
    - file:
        path=/home/isucon/isucon6f/worker
        mode=0755

- hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: bench (systemd)
      copy: src=../files/etc/systemd/system/isucon6-worker.service dest=/etc/systemd/system/isucon6-worker.service owner=root mode=644
    - name: enable bench worker
      service: name=isucon6-worker state=running enabled=true
