---
- name: mkdir ssh
  file:
    path=/home/isucon/.ssh/
    state=directory
    mode=700
    owner=isucon
    group=isucon
- name: deploy key
  become_user: isucon
  copy:
    src=home/isucon/.ssh/id_rsa
    dest=/home/isucon/.ssh/id_rsa
    mode=600
    owner=isucon
    group=isucon
- name: git clone
  become_user: isucon
  git:
    repo=git@github.com:catatsuy/isucon6-final.git
    dest=/home/isucon/repos
    accept_hostkey=yes
- name: remove webapp directory
  file:
    path=/home/isucon/webapp/
    state=absent
- name: move webapp directory
  command: "mv /home/isucon/repos/webapp /home/isucon/webapp"
- name: remove repos directory
  file:
    path=/home/isucon/repos/
    state=absent
- name: remove ssh directory
  file:
    path=/home/isucon/.ssh/
    state=absent
- name: symoblic link docker-compose.yml
  become_user: isucon
  file:
    src=/home/isucon/webapp/docker-compose-php.yml
    dest=/home/isucon/webapp/docker-compose.yml
    state=link
- name: remove .gitignore
  file:
    path=/home/isucon/webapp/.gitignore
    state=absent
- name: place the file of systemd
  copy:
    src=etc/systemd/system/isu.service
    dest=/etc/systemd/system/isu.service
    owner=root
    mode=644
  notify: reload systemctl
- name: running default application
  service: name=isu state=running enabled=true
