---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
    - raw: apt-get update -qq
    - raw: apt-get install -qq python

- hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: apt update
      apt: update_cache=yes
    - name: install dependency
      apt: name={{ item }}
      with_items:
        - git
        - curl
        - libreadline-dev
        - build-essential
        - libmysqlclient-dev
        - npm
