---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
    - debconf: name=mysql-server-5.7 question='mysql-server/root_password' value='root' vtype='password'
    - debconf: name=mysql-server-5.7 question='mysql-server/root_password_again' value='root' vtype='password'
    - apt: name=mysql-server-5.7 state=present
    - apt: name=mysql-client-5.7 state=present
    - name: copy my.cnf
      copy: src=../files/my.cnf dest=/etc/mysql/my.cnf owner=root group=root mode=644
      notify:
        - restart mysql
    - service: name=mysql state=running enabled=true
    - file: path=/home/isucon/isu6fportal/db owner=isucon group=isucon mode=755 state=directory recurse=yes
    - copy: src=../../../portal/db/schema.sql dest=/home/isucon/isu6fportal/db/schema.sql
    - shell: mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -uroot -proot mysql
    - shell: |
        MYSQL_PWD=root mysql -uroot -e "CREATE DATABASE isu6fportal"
        MYSQL_PWD=root mysql -uroot isu6fportal < /home/isucon/isu6fportal/db/schema.sql
  handlers:
    - name: restart mysql
      action: service name=mysql state=restarted
