- hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: isu6fportal (systemd)
      copy: src=../files/isu6fportal.service dest=/etc/systemd/system/isu6fportal.service owner=root mode=644
      register: service
    - name: systemctl daemon-reload
      command: systemctl daemon-reload
      when: service.changed
    - name: restart isu6fportal
      service: name=isu6fportal state=restarted enabled=true
      when: service.changed
