- hosts: all
  gather_facts: no
  become: yes
  become_user: isucon
  tasks:
    - name: mkdir isu6fportal
      file: path=/home/isucon/isu6fportal owner=isucon group=isucon mode=755 state=directory
    - name: upload ./portal
      copy: src=../../../portal/portal_linux_amd64 dest=/home/isucon/isu6fportal/portal mode=755
- hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: reload isu6fportal
      service: name=isu6fportal state=reloaded enabled=true
