- hosts: all
  become: yes
  become_user: isucon
  gather_facts: no
  tasks:
    - name: mkdir isu6fportal
      file: path=/home/isucon/isu6fportal/data owner=isucon group=isucon mode=755 state=directory
    - name: upload importteams
      copy: src=../../../portal/importteams_linux_amd64 dest=/home/isucon/isu6fportal/importteams mode=755
    - name: upload temas.tsv
      copy: src=../../../portal/data/teams.tsv dest=/home/isucon/isu6fportal/data/teams.tsv mode=755
    - shell: cat /home/isucon/isu6fportal/data/teams.tsv | /home/isucon/isu6fportal/importteams -u root -p root
