version: '2'
services:
  react_dev:
    build:
      context: ./react
      dockerfile: Dockerfile-dev
    volumes:
      - ./react/:/react/
      - ./ssl:/ssl:ro
    environment:
      SSL_KEY: /ssl/oreore.key
      SSL_CERT: /ssl/oreore.crt
      ISUCON_ENV: development
      API: http://api:80
      PORT: 443
    ports:
      - "443:443"
  react:
    build:
      context: ./react
      dockerfile: Dockerfile
    volumes:
      - ./ssl:/ssl:ro
    environment:
      SSL_KEY: /ssl/oreore.key
      SSL_CERT: /ssl/oreore.crt
      ISUCON_ENV: production
      NODE_ENV: production
      API: http://api:80
      PORT: 443
    ports:
      - "443:443"
