version: '2'
services:
  mysql:
    image: mysql
    volumes:
      - ./.data:/var/lib/mysql
      - ./sql:/sql
    environment:
      MYSQL_ROOT_PASSWORD: password
  api:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./php/html:/var/www/html:ro
    links:
      - mysql
    environment:
      ISUCON_ENV: production
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: isucon
      MYSQL_PASS: isucon
  react:
    build:
      context: ./react
      dockerfile: Dockerfile
    environment:
      API: http://api
    links:
      - api
    environment:
      API: http://api:80
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    command: "nginx"
    links:
      - api
      - react
