version: '2'
services:
  mysql:
    image: mysql
    volumes:
      - ./.data:/var/lib/mysql
      - ./sql:/sql
    environment:
      MYSQL_ROOT_PASSWORD: password
  api:
    build:
      context: ./go
      dockerfile: Dockerfile
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      ISUCON_ENV: production
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: isucon
      MYSQL_PASS: isucon
  react:
    build:
      context: ./react
      dockerfile: Dockerfile
    volumes:
      - ./ssl:/ssl:ro
    depends_on:
      - api
    links:
      - api
    environment:
      SSL_KEY: /ssl/oreore.key
      SSL_CERT: /ssl/oreore.crt
      ISUCON_ENV: production
      NODE_ENV: production
      API: http://api:80
      PORT: 443
    ports:
      - "443:443"
