version: '2'
services:
  # mysql
  mysql:
    image: mysql
    volumes:
      - /var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
  # php
  php:
    build: ./php
    ports:
      - "9901:9901"
  # react
  react:
    build: ./react
    ports:
      - "8800:8800"
    environment:
      API: http://php:9901
    links:
      - php
      - mysql
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    command: "nginx"
    links:
      - php
      - react
