version: '2'
services:
  mysql:
    image: mysql
    volumes:
      - ./.data:/var/lib/mysql
      - ./sql:/sql
    environment:
      MYSQL_ROOT_PASSWORD: password
  api:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./php/html:/var/www/html:ro
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      ISUCON_ENV: production
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: isucon
      MYSQL_PASS: isucon
  react_php:
    extends:
      file: docker-compose-react.yml
      service: react
    depends_on:
      - api
    links:
      - api
    ports:
      - "443:443"
