version: '2'
services:
  mysql:
    extends:
      file: docker-compose-mysql.yml
      service: mysql
  nodejs:
    build:
      context: ./nodejs
      dockerfile: Dockerfile-dev
    volumes:
      - ./nodejs/:/app
      - /app/node_modules
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      PORT: 80
      ISUCON_ENV: development
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: isucon
      MYSQL_PASS: isucon
    ports:
      - "80:80"
  react_dev_nodejs:
    extends:
      file: docker-compose-react.yml
      service: react_dev
    depends_on:
      - nodejs
    links:
      - nodejs
    environment:
      API: http://nodejs:80
